/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The customer's billing address; all fields in the address are optional. This address appears on customer invoices.
 */
export class BillingAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    /**
     * Two-letter country code (ISO 3166-1 alpha-2).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line1" })
    line1?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line2" })
    line2?: string;

    /**
     * ZIP or postal code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "state" })
    state?: string;
}
