/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Discount } from "./discount";
import { Expose, Transform, Type } from "class-transformer";

/**
 * A coupon represents a reusable discount configuration, and have an attached redemption code that can be issued to your end users. Coupons are most often used in self-serve signup or upgrade flows in your checkout experience or billing portal.
 *
 * @remarks
 *
 * To redeem a coupon, pass the `redemption_code` property in the [create subscription](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription) or [schedule plan change](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription-schedule-plan-change) request.
 *
 */
export class Coupon extends SpeakeasyBase {
    /**
     * An archived coupon can no longer be redeemed. Active coupons will have a value of null for `archived_at`; this field will be non-null for archived coupons.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "archived_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    archivedAt?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "discount" })
    @Type(() => Discount)
    discount: Discount;

    /**
     * This allows for a coupon's discount to apply for a limited time (determined in months); a `null` value here means "unlimited time".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "duration_in_months" })
    durationInMonths?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The maximum number of redemptions allowed for this coupon before it is exhausted; `null` here means "unlimited".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_redemptions" })
    maxRedemptions?: number;

    /**
     * This string can be used to redeem this coupon for a given subscription.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "redemption_code" })
    redemptionCode: string;

    /**
     * The number of times this coupon has been redeemed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "times_redeemed" })
    timesRedeemed?: number;
}

/**
 * A coupon represents a reusable discount configuration, and have an attached redemption code that can be issued to your end users. Coupons are most often used in self-serve signup or upgrade flows in your checkout experience or billing portal.
 *
 * @remarks
 *
 * To redeem a coupon, pass the `redemption_code` property in the [create subscription](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription) or [schedule plan change](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription-schedule-plan-change) request.
 *
 */
export class CouponInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "discount" })
    @Type(() => Discount)
    discount: Discount;

    /**
     * This allows for a coupon's discount to apply for a limited time (determined in months); a `null` value here means "unlimited time".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "duration_in_months" })
    durationInMonths?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The maximum number of redemptions allowed for this coupon before it is exhausted; `null` here means "unlimited".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_redemptions" })
    maxRedemptions?: number;

    /**
     * This string can be used to redeem this coupon for a given subscription.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "redemption_code" })
    redemptionCode: string;

    /**
     * The number of times this coupon has been redeemed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "times_redeemed" })
    timesRedeemed?: number;
}
