/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CreateDiscountDiscountType {
    Percentage = "percentage",
    Usage = "usage",
    Amount = "amount",
}

/**
 * The subscription's override discount for this price.
 */
export class CreateDiscount extends SpeakeasyBase {
    /**
     * Only allowed if discount_type is amount
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount_discount" })
    amountDiscount?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "discount_type" })
    discountType?: CreateDiscountDiscountType;

    /**
     * Only allowed if discount_type is percentage
     */
    @SpeakeasyMetadata()
    @Expose({ name: "percentage_discount" })
    percentageDiscount?: string;

    /**
     * Only allowed if discount_type is usage
     */
    @SpeakeasyMetadata()
    @Expose({ name: "usage_discount" })
    usageDiscount?: string;
}
