/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Discount } from "./discount";
import { Expose, Type } from "class-transformer";

export class CreditNoteLineItemSubLineItems extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;
}

export class CreditNoteLineItemTaxAmounts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate_description" })
    taxRateDescription: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate_percentage" })
    taxRatePercentage: string;
}

export class CreditNoteLineItem extends SpeakeasyBase {
    /**
     * The amount of the line item, including any line item minimums and discounts
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: string;

    @SpeakeasyMetadata()
    @Expose({ name: "discounts" })
    @Type(() => Discount)
    discounts: Discount;

    /**
     * The Orb id of this resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The name of the corresponding invoice line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * An optional quantity credited.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * Any sub line items that may be credited.
     */
    @SpeakeasyMetadata({ elemType: CreditNoteLineItemSubLineItems })
    @Expose({ name: "sub_line_items" })
    @Type(() => CreditNoteLineItemSubLineItems)
    subLineItems: CreditNoteLineItemSubLineItems[];

    /**
     * The amount of the line item, excluding any line item minimums and discounts
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subtotal" })
    subtotal: string;

    /**
     * Any tax amounts applied onto the line item.
     */
    @SpeakeasyMetadata({ elemType: CreditNoteLineItemTaxAmounts })
    @Expose({ name: "tax_amounts" })
    @Type(() => CreditNoteLineItemTaxAmounts)
    taxAmounts: CreditNoteLineItemTaxAmounts[];
}
