/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum DiscountDiscountType {
    Percentage = "percentage",
    Trial = "trial",
    Usage = "usage",
    Amount = "amount",
}

export class Discount extends SpeakeasyBase {
    /**
     * Only available if discount_type is `amount`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount_discount" })
    amountDiscount?: string;

    /**
     * List of price_ids that this discount applies to. For plan/plan phase discounts, this can be a subset of prices.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "applies_to_price_ids" })
    appliesToPriceIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "discount_type" })
    discountType: DiscountDiscountType;

    /**
     * Only available if discount_type is `percentage`.This is a number between 0 and 1.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "percentage_discount" })
    percentageDiscount?: number;

    /**
     * Only available if discount_type is `trial`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "trial_amount_discount" })
    trialAmountDiscount?: string;

    /**
     * Only available if discount_type is `usage`. Number of usage units that this discount is for
     */
    @SpeakeasyMetadata()
    @Expose({ name: "usage_discount" })
    usageDiscount?: number;
}
