/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MinimumAmount extends SpeakeasyBase {
    /**
     * List of price_ids that this minimum amount applies to. For plan/plan phase minimums, this can be a subset of prices.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "applies_to_price_ids" })
    appliesToPriceIds: string[];

    /**
     * Minimum amount applied
     */
    @SpeakeasyMetadata()
    @Expose({ name: "minimum_amount" })
    minimumAmount: string;
}
