/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
 */
export class AmendUsageRequestBodyEventsProperties extends SpeakeasyBase {}

export class AmendUsageRequestBodyEvents extends SpeakeasyBase {
    /**
     * A name to meaningfully identify the action or event type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_name" })
    eventName: string;

    /**
     * A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "properties" })
    @Type(() => AmendUsageRequestBodyEventsProperties)
    properties: AmendUsageRequestBodyEventsProperties;

    /**
     * An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent the time that usage was recorded, and is particularly important to attribute usage to a given billing period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    timestamp: string;
}

export class AmendUsageRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: AmendUsageRequestBodyEvents })
    @Expose({ name: "events" })
    @Type(() => AmendUsageRequestBodyEvents)
    events: AmendUsageRequestBodyEvents[];
}

export class AmendUsageRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: AmendUsageRequestBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=customer_id" })
    customerId: string;

    /**
     * This bound is exclusive (i.e. events before this timestamp will be updated)
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=timeframe_end" })
    timeframeEnd: Date;

    /**
     * This bound is inclusive (i.e. events with this timestamp onward, inclusive will be updated)
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=timeframe_start" })
    timeframeStart: Date;
}

export class AmendUsage400ApplicationJSONValidationErrors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "idempotency_key" })
    idempotencyKey?: string;

    /**
     * An array of strings corresponding to each validation failure
     */
    @SpeakeasyMetadata()
    @Expose({ name: "validation_errors" })
    validationErrors?: string[];
}

/**
 * Bad Request
 */
export class AmendUsage400ApplicationJSON extends SpeakeasyBase {
    /**
     * HTTP Code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: number;

    /**
     * Error message
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;

    /**
     * Contains all failing validation events.
     */
    @SpeakeasyMetadata({ elemType: AmendUsage400ApplicationJSONValidationErrors })
    @Expose({ name: "validation_errors" })
    @Type(() => AmendUsage400ApplicationJSONValidationErrors)
    validationErrors: AmendUsage400ApplicationJSONValidationErrors[];
}

export class AmendUsage200ApplicationJSONDuplicate extends SpeakeasyBase {}

/**
 * OK
 */
export class AmendUsage200ApplicationJSON extends SpeakeasyBase {
    /**
     * An array of strings, corresponding to idempotency_key's marked as duplicates (previously ingested)
     */
    @SpeakeasyMetadata({ elemType: AmendUsage200ApplicationJSONDuplicate })
    @Expose({ name: "duplicate" })
    @Type(() => AmendUsage200ApplicationJSONDuplicate)
    duplicate?: AmendUsage200ApplicationJSONDuplicate[];

    /**
     * An array of strings, corresponding to idempotency_key's which were successfully ingested.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ingested" })
    ingested?: string[];
}

export class AmendUsageResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    amendUsage200ApplicationJSONObject?: AmendUsage200ApplicationJSON;

    /**
     * Bad Request
     */
    @SpeakeasyMetadata()
    amendUsage400ApplicationJSONObject?: AmendUsage400ApplicationJSON;
}
