/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Transform, Type } from "class-transformer";

export enum CreateLedgerEntryRequestBodyEntryType {
    Increment = "increment",
    Decrement = "decrement",
    ExpirationChange = "expiration_change",
}

/**
 * Passing `invoice_settings` automatically generates an invoice for the newly added credits. If `invoice_settings` is passed, you must specify `per_unit_cost_basis`, as the calculation of the invoice total is done on that basis.
 */
export class CreateLedgerEntryRequestBodyInvoiceSettings extends SpeakeasyBase {
    /**
     * Whether the credits purchase invoice should auto collect with the customer's saved payment method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "auto_collection" })
    autoCollection: boolean;

    /**
     * An optional memo to display on the invoice.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo?: string;

    /**
     * The net terms determines the difference between the invoice date and the issue date for the invoice. If you intend the invoice to be due on issue, set this to 0.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "net_terms" })
    netTerms: number;
}

/**
 * User-specified key/value pairs for the ledger entry resource.
 */
export class CreateLedgerEntryRequestBodyMetadata extends SpeakeasyBase {}

export class CreateLedgerEntryRequestBody extends SpeakeasyBase {
    /**
     * The number of credits to effect. Note that this is required for increment or decrement operations.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * The ID of the block affected by an `expiration_change`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "block_id" })
    blockId?: string;

    /**
     * Optional metadata that can be specified when adding ledger results via the API. For example, this can be used to note an increment refers to trial credits, or for noting corrections as a result of an incident, etc.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entry_type" })
    entryType: CreateLedgerEntryRequestBodyEntryType;

    /**
     * A future date (specified in YYYY-MM-DD format) that denotes when this credit balance should expire.
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiry_date" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    expiryDate?: RFCDate;

    /**
     * Passing `invoice_settings` automatically generates an invoice for the newly added credits. If `invoice_settings` is passed, you must specify `per_unit_cost_basis`, as the calculation of the invoice total is done on that basis.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_settings" })
    @Type(() => CreateLedgerEntryRequestBodyInvoiceSettings)
    invoiceSettings?: CreateLedgerEntryRequestBodyInvoiceSettings;

    /**
     * User-specified key/value pairs for the ledger entry resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => CreateLedgerEntryRequestBodyMetadata)
    metadata?: CreateLedgerEntryRequestBodyMetadata;

    /**
     * Can only be specified when `entry_type=increment`. How much, in USD, a customer paid for a single credit in this block
     */
    @SpeakeasyMetadata()
    @Expose({ name: "per_unit_cost_basis" })
    perUnitCostBasis?: string;

    /**
     * A future date (specified in YYYY-MM-DD) used for `expiration_change`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "target_expiry_date" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    targetExpiryDate?: RFCDate;
}

export class CreateLedgerEntryRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: CreateLedgerEntryRequestBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=customer_id" })
    customerId: string;
}

export class CreateLedgerEntryResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    creditLedgerEntry?: shared.CreditLedgerEntry;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
